import numpy as np
mylist = [[109, "Aggressive Fighting"],
    [25, "Alchemy"],
    [130, "Animal Husbandry"],
    [129, "Animal Taming"],
    [120, "Archaeology"],
    [16, "Archery"],
    [22, "Armour Smithing"],
    [11, "Axes"],
    [62, "Baking"],
    [135, "Ballistae"],
    [63, "Beverages"],
    [59, "Blacksmithing"],
    [54, "Blades Smithing"],
    [1, "Body"],
    [3, "Body Control"],
    [4, "Body Stamina"],
    [5, "Body Strength"],
    [122, "Botanizing"],
    [103, "Bowyery"],
    [77, "Butchering"],
    [73, "Butchering Knife"],
    [78, "Carpentry"],
    [72, "Carving Knife"],
    [128, "Catapults"],
    [56, "Chain Armour Smithing"],
    [118, "Channeling"],
    [123, "Climbing"],
    [52, "Cloth Tailoring"],
    [14, "Clubs"],
    [97, "Coal-Making"],
    [19, "Cooking"],
    [60, "Dairy Food Making"],
    [110, "Defensive Fighting"],
    [44, "Digging"],
    [119, "Exorcism"],
    [33, "Farming"],
    [28, "Fighting"],
    [102, "Fine Carpentry"],
    [79, "Firemaking"],
    [112, "First Aid"],
    [94, "Fishing"],
    [104, "Fletching"],
    [121, "Foraging"],
    [38, "Forestry"],
    [36, "Gardening"],
    [70, "Halberd"],
    [91, "Hammer"],
    [15, "Hammers"],
    [50, "Hatchet"],
    [29, "Healing"],
    [61, "Hot Food Cooking"],
    [88, "Huge Axe"],
    [75, "Huge Club"],
    [101, "Jewelry Smithing"],
    [12, "Knives"],
    [87, "Large Axe"],
    [65, "Large Maul"],
    [85, "Large Metal Shield"],
    [83, "Large Wooden Shield"],
    [51, "Leather working"],
    [125, "Lock Picking"],
    [95, "Locksmithing"],
    [132, "Long Bow"],
    [69, "Long Spear"],
    [64, "Longsword"],
    [53, "Masonry"],
    [13, "Mauls"],
    [37, "Meditating"],
    [133, "Medium Bow"],
    [66, "Medium Maul"],
    [86, "Medium Metal Shield"],
    [82, "Medium Wooden Shield"],
    [99, "Metallurgy"],
    [115, "Milking"],
    [98, "Milling"],
    [0, "Mind"],
    [6, "Mind Logic"],
    [7, "Mind Speed"],
    [43, "Mining"],
    [23, "Misc Items"],
    [100, "Natural Substances"],
    [26, "Nature"],
    [111, "Normal Fighting"],
    [34, "Papyrusmaking"],
    [92, "Paving"],
    [45, "Pick axe"],
    [57, "Plate Armour Smithing"],
    [17, "Polearms"],
    [47, "Pottery"],
    [117, "Praying"],
    [116, "Preaching"],
    [93, "Prospecting"],
    [106, "Puppeteering"],
    [39, "Rake"],
    [30, "Religion"],
    [96, "Repairing"],
    [137, "Restoration"],
    [48, "Ropemaking"],
    [76, "Saw"],
    [40, "Scythe"],
    [114, "Shield Bashing"],
    [58, "Shield Smithing"],
    [24, "Shields"],
    [134, "Ship Building"],
    [131, "Short Bow"],
    [89, "Shortsword"],
    [46, "Shovel"],
    [41, "Sickle"],
    [42, "Small Axe"],
    [67, "Small Maul"],
    [84, "Small Metal Shield"],
    [81, "Small Wooden Shield"],
    [20, "Smithing"],
    [2, "Soul"],
    [8, "Soul Depth"],
    [9, "Soul Strength"],
    [71, "Staff"],
    [126, "Stealing"],
    [74, "Stone Chisel"],
    [124, "Stone Cutting"],
    [10, "Swords"],
    [18, "Tailoring"],
    [113, "Taunting"],
    [35, "Thatching"],
    [31, "Thievery"],
    [107, "Toy Making"],
    [27, "Toys"],
    [80, "Tracking"],
    [127, "Traps"],
    [136, "Trebuchets"],
    [90, "Two Handed Sword"],
    [32, "War Machines"],
    [68, "Warhammer"],
    [55, "Weapon Heads Smithing"],
    [21, "Weapon Smithing"],
    [108, "Weaponless Fighting"],
    [49, "Woodcutting"],
    [105, "Yoyo"]]

result = ['']*138
for paire in mylist:
    result[paire[0]] = paire[1]

print(result[105])